# Generated by Django 2.2.5 on 2020-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
